create table bb_category (
    id varchar(255) primary key,
    name jsonb,
    description jsonb,
    attribute_template jsonb
);

create table bb_supplier (
    id varchar(255) primary key,
    name jsonb,
    description jsonb,
    contact_info varchar(255),
    onboarding_rules jsonb
);

create table bb_user (
    id bigint primary key,
    name varchar(255) not null,
    username varchar(100),
    password_hash varchar(255),
    enabled boolean not null default true,
    role varchar(255) not null,
    rating double precision not null default 0,
    phone varchar(255),
    email varchar(255),
    note varchar(2000),
    default_address jsonb,
    social_accounts jsonb,
    constraint uk_bb_user_username unique (username),
    constraint ck_bb_user_role check (role in ('CUSTOMER', 'AGENT', 'MERCHANT'))
);

create table bb_trip (
    id bigint primary key,
    agent_id bigint not null,
    origin varchar(255) not null,
    destination varchar(255) not null,
    depart_date date not null,
    capacity integer not null,
    reserved_capacity integer not null default 0,
    status varchar(255) not null,
    status_updated_at timestamp(6),
    constraint fk_bb_trip_agent foreign key (agent_id) references bb_user (id),
    constraint ck_bb_trip_status check (status in ('DRAFT', 'PUBLISHED', 'IN_PROGRESS', 'COMPLETED', 'SETTLED'))
);

create table bb_product (
    id varchar(255) primary key,
    name jsonb,
    description jsonb,
    brand varchar(255),
    base_price double precision not null default 0,
    weight double precision,
    volume double precision,
    media_gallery jsonb,
    storage_condition varchar(255),
    order_method varchar(255),
    category_id varchar(255),
    merchant_skus jsonb,
    item_number varchar(255),
    price_tiers jsonb,
    is_recommended boolean not null default false,
    is_temporary boolean not null default false,
    visibility_status varchar(255) not null default 'PUBLIC',
    updated_at timestamp(6),
    constraint fk_bb_product_category foreign key (category_id) references bb_category (id),
    constraint uk_bb_product_item_number unique (item_number),
    constraint ck_bb_product_storage_condition check (storage_condition is null or storage_condition in ('AMBIENT', 'FRESH', 'CHILLED', 'FROZEN')),
    constraint ck_bb_product_order_method check (order_method is null or order_method in ('PRE_ORDER', 'DIRECT_BUY')),
    constraint ck_bb_product_visibility_status check (visibility_status in ('DRAFTER_ONLY', 'PUBLIC'))
);

create table bb_merchant_sku (
    id varchar(255) primary key,
    product_id varchar(255),
    merchant_id varchar(255),
    sku_code varchar(255),
    last_price double precision not null default 0,
    stock_status varchar(255),
    constraint fk_bb_merchant_sku_product foreign key (product_id) references bb_product (id),
    constraint fk_bb_merchant_sku_merchant foreign key (merchant_id) references bb_supplier (id),
    constraint uk_bb_merchant_sku_merchant_id_sku_code unique (merchant_id, sku_code),
    constraint ck_bb_merchant_sku_stock_status check (stock_status is null or stock_status in ('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK'))
);

create table bb_order_header (
    id bigint primary key,
    business_id varchar(64) not null,
    customer_id bigint,
    trip_id bigint,
    desired_delivery_window varchar(255),
    created_at timestamp(6),
    status varchar(255) not null,
    status_updated_at timestamp(6),
    payment_method varchar(255),
    payment_status varchar(255) not null,
    total_amount double precision not null default 0,
    receipt_confirmed_at timestamp(6),
    receipt_confirmed_by varchar(255),
    billing_confirmed_at timestamp(6),
    billing_confirmed_by varchar(255),
    delivery_status varchar(255) not null,
    lines jsonb,
    constraint uk_bb_order_header_business_id unique (business_id),
    constraint fk_bb_order_header_customer foreign key (customer_id) references bb_user (id),
    constraint fk_bb_order_header_trip foreign key (trip_id) references bb_trip (id),
    constraint ck_bb_order_header_status check (status in ('NEW', 'CONFIRMED', 'PURCHASED', 'DELIVERED', 'SETTLED', 'CANCELLED')),
    constraint ck_bb_order_header_payment_method check (payment_method is null or payment_method in ('ALIPAY', 'WECHAT', 'CASH')),
    constraint ck_bb_order_header_payment_status check (payment_status in ('UNPAID', 'PAID', 'REFUNDED')),
    constraint ck_bb_order_header_delivery_status check (delivery_status in ('PENDING_DELIVERY', 'READY_FOR_DELIVERY', 'DELIVERING', 'DELIVERED'))
);

create table bb_chat_message (
    id bigint generated by default as identity primary key,
    order_id bigint,
    trip_id bigint,
    sender_id varchar(255),
    recipient_id varchar(255),
    content text,
    type varchar(255),
    metadata jsonb,
    created_at timestamp(6)
);

create table partner_wallets (
    id bigint generated by default as identity primary key,
    partner_id varchar(255) not null,
    balance double precision not null,
    currency varchar(255) not null,
    updated_at timestamp(6) not null,
    constraint uk_partner_wallets_partner_id unique (partner_id)
);

create table wallet_transactions (
    id bigint generated by default as identity primary key,
    partner_id varchar(255) not null,
    amount double precision not null,
    type varchar(255) not null,
    trip_id bigint not null,
    created_at timestamp(6) not null,
    constraint fk_wallet_transactions_trip foreign key (trip_id) references bb_trip (id)
);

create table bb_procurement_receipt (
    id bigint generated by default as identity primary key,
    trip_id bigint,
    file_name varchar(255),
    original_object_key varchar(255),
    original_image_url varchar(255),
    thumbnail_object_key varchar(255),
    thumbnail_url varchar(255),
    processing_status varchar(255),
    uploaded_at timestamp(6),
    updated_at timestamp(6),
    source_image_base64 varchar(200000),
    reconciliation_result jsonb,
    raw_recognition_result jsonb,
    manual_reconciliation_result jsonb,
    constraint fk_bb_procurement_receipt_trip foreign key (trip_id) references bb_trip (id)
);

create table bb_trip_expense (
    id bigint generated by default as identity primary key,
    trip_id bigint,
    cost double precision not null default 0,
    category varchar(255),
    receipt_object_key varchar(255),
    receipt_thumbnail_url varchar(255),
    ocr_status varchar(255),
    created_at timestamp(6),
    constraint fk_bb_trip_expense_trip foreign key (trip_id) references bb_trip (id)
);

create table bb_trip_logistics_tracking (
    id bigint generated by default as identity primary key,
    trip_id bigint,
    tracking_number varchar(255),
    channel varchar(255),
    provider varchar(255),
    status varchar(255),
    last_message varchar(255),
    settlement_reminder_triggered boolean not null default false,
    last_checked_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint fk_bb_trip_logistics_tracking_trip foreign key (trip_id) references bb_trip (id),
    constraint ck_bb_trip_logistics_tracking_channel check (channel is null or channel in ('DOMESTIC', 'INTERNATIONAL')),
    constraint ck_bb_trip_logistics_tracking_provider check (provider is null or provider in ('MOCK', 'TRACK17')),
    constraint ck_bb_trip_logistics_tracking_status check (status is null or status in ('PENDING', 'IN_TRANSIT', 'DELIVERED', 'EXCEPTION'))
);

create table bb_trip_profit_share_config (
    trip_id bigint primary key,
    purchaser_ratio_percent double precision not null default 0,
    promoter_ratio_percent double precision not null default 0,
    updated_at timestamp(6),
    constraint fk_bb_trip_profit_share_config_trip foreign key (trip_id) references bb_trip (id)
);

create table bb_customer_payment_ledger (
    id bigint generated by default as identity primary key,
    trip_id bigint,
    business_id varchar(255),
    customer_id bigint,
    amount double precision not null default 0,
    payment_method varchar(255),
    note varchar(255),
    created_at timestamp(6),
    operator varchar(255),
    constraint fk_bb_customer_payment_ledger_trip foreign key (trip_id) references bb_trip (id),
    constraint fk_bb_customer_payment_ledger_customer foreign key (customer_id) references bb_user (id)
);

create table bb_financial_audit_log (
    id bigint generated by default as identity primary key,
    trip_id bigint not null,
    action_type varchar(64) not null,
    operator_name varchar(64) not null,
    original_value text not null,
    modified_value text not null,
    previous_hash varchar(128) not null,
    current_hash varchar(128) not null,
    created_at timestamp(6) not null,
    constraint fk_bb_financial_audit_log_trip foreign key (trip_id) references bb_trip (id)
);

create table bb_experience_mapping (
    id bigint generated by default as identity primary key,
    fuzzy_term varchar(255) not null,
    mapped_name varchar(255) not null,
    updated_at timestamp(6) with time zone not null,
    constraint uk_bb_experience_mapping_fuzzy_term unique (fuzzy_term)
);

alter table bb_chat_message
    add constraint fk_bb_chat_message_order foreign key (order_id) references bb_order_header (id);

alter table bb_chat_message
    add constraint fk_bb_chat_message_trip foreign key (trip_id) references bb_trip (id);

create index idx_bb_trip_agent_status_depart on bb_trip (agent_id, status, depart_date);
create index idx_bb_product_category_id on bb_product (category_id);
create index idx_bb_order_header_trip_created on bb_order_header (trip_id, created_at, id);
create index idx_bb_order_header_customer_created on bb_order_header (customer_id, created_at, id);
create index idx_bb_order_header_status_created on bb_order_header (status, created_at, id);
create index idx_chat_message_order_id_id on bb_chat_message (order_id, id);
create index idx_chat_message_trip_id_id on bb_chat_message (trip_id, id);
create index idx_chat_message_sender_recipient_id on bb_chat_message (sender_id, recipient_id, id);
create index idx_partner_wallets_partner_id on partner_wallets (partner_id);
create index idx_wallet_transactions_partner_created on wallet_transactions (partner_id, created_at desc);
create index idx_wallet_transactions_trip_id on wallet_transactions (trip_id);
create index idx_bb_procurement_receipt_trip_uploaded on bb_procurement_receipt (trip_id, uploaded_at desc, id desc);
create index idx_bb_trip_expense_trip_created on bb_trip_expense (trip_id, created_at desc, id desc);
create index idx_bb_trip_logistics_trip_updated on bb_trip_logistics_tracking (trip_id, updated_at desc, id desc);
create index idx_bb_customer_payment_trip_business_created on bb_customer_payment_ledger (trip_id, business_id, created_at, id);
create index idx_bb_customer_payment_customer_created on bb_customer_payment_ledger (customer_id, created_at, id);
create index idx_bb_financial_audit_trip_created on bb_financial_audit_log (trip_id, created_at desc, id desc);
create index idx_bb_merchant_sku_product_id on bb_merchant_sku (product_id);
create index idx_bb_merchant_sku_merchant_id on bb_merchant_sku (merchant_id);
