create table bb_refresh_token_session (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash varchar(128) not null,
    family_id varchar(64) not null,
    rotation_source_id bigint,
    client_fingerprint varchar(255),
    created_at timestamp(6) with time zone not null,
    last_used_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    revoked_at timestamp(6) with time zone,
    revocation_reason varchar(64),
    constraint fk_bb_refresh_token_session_user foreign key (user_id) references bb_user (id),
    constraint fk_bb_refresh_token_session_rotation_source foreign key (rotation_source_id) references bb_refresh_token_session (id),
    constraint uk_bb_refresh_token_session_token_hash unique (token_hash)
);

create index idx_bb_refresh_token_session_user_exp on bb_refresh_token_session (user_id, expires_at desc);
create index idx_bb_refresh_token_session_family on bb_refresh_token_session (family_id);
